version: '3'
services:
  game: # First server/container
    image: tower-defense-game
    networks: # Network to join
      - game-network_YML
    volumes:
      - game-data_YML:/data
networks:
  game-network_YML: # Network definition
    driver: bridge
volumes:
  game-data_YML: # Volume definition
    driver: local
